### ISSUE TITLE
Call host/s inside the fixture

### ISSUE THREAD

**Issue by madhuriupadhye** [SSSD/sssd-test-framework#104]
Looking for something like this, 

@pytest.fixture(scope="module")
@pytest.mark.topology(KnownTopology.IPA)
def umockdev_ipaotpd_update(ipa: IPA)
...
...

**Comment by pbrezina** [comment]
This currently can't be done, but I opened https://github.com/pytest-dev/pytest/issues/12376

But I implemented a workaroud: https://github.com/next-actions/pytest-mh/pull/55 so you can use `ipa = mh.fixtures["ipa"]`
